version: "3"

services:

  postgres:
    image: postgres:16-alpine
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: "java_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "8432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    depends_on:
      - postgres
    build: .
    volumes:
      - .:/workdir
    ports:
      - "8080:8080"
    extra_hosts:
      - "dockerhost:host-gateway"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/java_db
#    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /app/target/*.jar
    command: mvn spring-boot:run



volumes:
  postgres_data: